runtime: python311  # or python310, python39, etc.

entrypoint: gunicorn -b :$PORT main:app  # Replace 'main' with your Python filename (without .py)

instance_class: F1  # Optional: Choose instance class (F1, F2, F4, etc.)

env_variables:
  FLASK_ENV: "production"
  DEBUG: "false"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

# https://github.com/brijeshsmita/executive-eLearning.git
